version: '3'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.5.0
    restart: on-failure
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-data:/data.ms
    environment:
      MEILI_MASTER_KEY: modrinth
      MEILI_HTTP_PAYLOAD_SIZE_LIMIT: 107374182400
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
volumes:
  meilisearch-data: